name: CI with Pytest in Docker

on:
  pull_request:
    branches: [ "develop", "main" ]

env:
  TEST_IMAGE_NAME: fintory-server-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for Test
      id: build-test-image
      run: docker build --target tester -t ${{ env.TEST_IMAGE_NAME }} .

    - name: Run Test
      id: run-test
      run: |
        docker run --rm \
        -e DATABASE_URL="mysql+pymysql://localhost:3306" \
          ${{ env.TEST_IMAGE_NAME }}